{{- if and .Values.tls.enabled (or .Values.tls.caCert .Values.tls.caKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ include "etcdauto.namespace" . }}
  labels:
    {{- include "etcdauto.labels" . | nindent 4 }}
type: Opaque
immutable: true
data:
  {{- if .Values.tls.caCert }}
  ca.pem: {{ .Values.tls.caCert }}
  {{- end }}
  {{- if .Values.tls.caKey }}
  ca-key.pem: {{ .Values.tls.caKey }}
  {{- end }}
{{- end }}
