name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

env:
  BUILD_PLATFORM: linux/amd64,linux/arm64
  ONLINE_REGISTER: ghcr.io
  ONLINE_REGISTER_USER: ${{ github.actor }}
  ONLINE_REGISTER_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}

jobs:
  release:
    if: github.repository == 'yylt/etcdauto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - name: Login to online register
        uses: docker/login-action@v4
        with:
          username: ${{ env.ONLINE_REGISTER_USER }}
          password: ${{ env.ONLINE_REGISTER_PASSWORD }}
          registry: ${{ env.ONLINE_REGISTER }}

      - name: Build and Push Image
        uses: docker/build-push-action@v7
        id: docker_build_release
        with:
          context: .
          file: Dockerfile
          push: true
          provenance: false
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
            ${{ env.ONLINE_REGISTER }}/${{ github.repository }}:${{ github.ref_name }},
            ${{ env.ONLINE_REGISTER }}/${{ github.repository }}:latest
